# Generated by Django 4.2.7 on 2025-11-23 21:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_id", models.IntegerField()),
                ("session", models.CharField(max_length=255, unique=True)),
                ("chapter_number", models.FloatField()),
                ("volume", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "translator",
                    models.CharField(blank=True, default="Unknown", max_length=100),
                ),
                ("pages_count", models.PositiveIntegerField(default=0)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["manga", "chapter_number"],
            },
        ),
        migrations.CreateModel(
            name="Manga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manga_id", models.IntegerField(default=0)),
                ("manga_session", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "alternative_titles",
                    models.TextField(blank=True, help_text="Separate with commas"),
                ),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.URLField(blank=True, max_length=500)),
                ("banner_url", models.URLField(blank=True, max_length=500)),
                (
                    "manga_type",
                    models.CharField(
                        choices=[
                            ("manga", "Manga"),
                            ("manhwa", "Manhwa"),
                            ("manhua", "Manhua"),
                            ("webtoon", "Webtoon"),
                        ],
                        default="manga",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("hiatus", "Hiatus"),
                            ("dropped", "Dropped"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("total_chapters", models.PositiveIntegerField(default=0)),
                ("current_chapter", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("bookmarks", models.PositiveIntegerField(default=0)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("artist", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("serialization", models.CharField(blank=True, max_length=100)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True, max_length=160)),
                ("keywords", models.CharField(blank=True, max_length=255)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_adult", models.BooleanField(default=False)),
                ("is_colored", models.BooleanField(default=False)),
                ("released_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MangaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Manga Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MangaGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReadingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField(default=1)),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manga.chapter",
                    ),
                ),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="manga.manga"
                    ),
                ),
            ],
            options={
                "ordering": ["-last_read_at"],
            },
        ),
        migrations.CreateModel(
            name="MangaRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ratings",
                        to="manga.manga",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manga",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manga.mangacategory",
            ),
        ),
        migrations.AddField(
            model_name="manga",
            name="genres",
            field=models.ManyToManyField(blank=True, to="manga.mangagenre"),
        ),
        migrations.CreateModel(
            name="DownloadLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("low", "Low Quality"),
                            ("medium", "Medium Quality"),
                            ("high", "High Quality"),
                            ("original", "Original Quality"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("cbz", "CBZ"),
                            ("zip", "ZIP"),
                            ("epub", "EPUB"),
                        ],
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("file_size", models.CharField(blank=True, max_length=20)),
                ("host_name", models.CharField(default="unknown", max_length=50)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_links",
                        to="manga.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["quality", "format"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="manga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="manga.manga",
            ),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("plan_to_read", "Plan to Read"),
                            ("reading", "Currently Reading"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("dropped", "Dropped"),
                        ],
                        default="plan_to_read",
                        max_length=20,
                    ),
                ),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="manga.manga"
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="MangaPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("image_url", models.URLField(max_length=1000)),
                (
                    "local_image",
                    models.ImageField(blank=True, null=True, upload_to="manga_pages/"),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="manga.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "page_number"],
                "indexes": [
                    models.Index(
                        fields=["chapter", "page_number"],
                        name="manga_manga_chapter_79aadc_idx",
                    )
                ],
                "unique_together": {("chapter", "page_number")},
            },
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(
                fields=["manga_id"], name="manga_manga_manga_i_d7a84b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(fields=["status"], name="manga_manga_status_1bbfac_idx"),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(
                fields=["is_featured"], name="manga_manga_is_feat_852cd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(
                fields=["is_trending"], name="manga_manga_is_tren_1d48d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(fields=["year"], name="manga_manga_year_5097b2_idx"),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(fields=["title"], name="manga_manga_title_b5a3dc_idx"),
        ),
        migrations.AddIndex(
            model_name="downloadlink",
            index=models.Index(
                fields=["chapter", "quality"], name="manga_downl_chapter_296981_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadlink",
            index=models.Index(fields=["format"], name="manga_downl_format_0a6775_idx"),
        ),
        migrations.AddIndex(
            model_name="downloadlink",
            index=models.Index(
                fields=["is_active"], name="manga_downl_is_acti_62d861_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["chapter_id"], name="manga_chapt_chapter_625bf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["manga", "chapter_number"],
                name="manga_chapt_manga_i_d04498_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["publish_date"], name="manga_chapt_publish_954b35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("manga", "chapter_number")},
        ),
    ]
