# Generated by Django 4.2.7 on 2025-11-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="wp_author_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="wp_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="wp_featured_media",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="wp_link",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="manga",
            name="wp_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="wp_post_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="manga",
            name="meta_description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(
                fields=["wp_post_id"], name="manga_manga_wp_post_ef1d1b_idx"
            ),
        ),
    ]
