# Generated by Django 4.2.7 on 2025-11-24 00:31

from django.db import migrations, models
import manga.models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0002_manga_wp_author_id_manga_wp_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="session",
            field=models.CharField(
                default=manga.models.generate_chapter_session,
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="manga_session",
            field=models.CharField(
                default=manga.models.generate_manga_session, max_length=255, unique=True
            ),
        ),
    ]
