# Generated by Django 4.2.7 on 2025-12-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0003_alter_chapter_session_alter_manga_manga_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Commenter's name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional email (not displayed)",
                        max_length=254,
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False if you want to moderate comments",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="manga.chapter",
                    ),
                ),
                (
                    "manga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="manga.manga",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="manga.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["manga", "is_approved", "is_active"],
                        name="manga_comme_manga_i_2d32c1_idx",
                    ),
                    models.Index(
                        fields=["chapter", "is_approved", "is_active"],
                        name="manga_comme_chapter_8dbfd5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="manga_comme_created_be7c9e_idx"
                    ),
                ],
            },
        ),
    ]
