# Generated by Django 4.2.7 on 2025-11-23 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anime_id", models.IntegerField(default=0)),
                ("anime_session", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("poster_url", models.URLField(blank=True, max_length=500)),
                ("cover_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("upcoming", "Upcoming"),
                            ("dropped", "Dropped"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("total_episodes", models.PositiveIntegerField(default=0)),
                ("current_episode", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("fall", "Fall"),
                            ("winter", "Winter"),
                        ],
                        max_length=10,
                    ),
                ),
                ("studio", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=50)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True, max_length=160)),
                ("keywords", models.CharField(blank=True, max_length=255)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_adult", models.BooleanField(default=False)),
                ("aired_from", models.DateField(blank=True, null=True)),
                ("aired_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnimeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Anime Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnimeGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_id", models.IntegerField()),
                ("session", models.CharField(max_length=255, unique=True)),
                ("episode_number", models.PositiveIntegerField()),
                ("episode2", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "fansub",
                    models.CharField(blank=True, default="Unknown", max_length=100),
                ),
                ("edition", models.CharField(blank=True, max_length=50)),
                ("snapshot_url", models.URLField(blank=True, max_length=500)),
                ("disc", models.CharField(blank=True, max_length=20)),
                ("post_url", models.URLField(blank=True, max_length=500)),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("is_filler", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="anime.anime",
                    ),
                ),
            ],
            options={
                "ordering": ["anime", "episode_number"],
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_watch", "Want to Watch"),
                            ("watching", "Currently Watching"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("dropped", "Dropped"),
                        ],
                        default="want_to_watch",
                        max_length=20,
                    ),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="anime.anime"
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_watched_at", models.DateTimeField(auto_now=True)),
                ("progress_seconds", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="anime.anime"
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_watched_at"],
            },
        ),
        migrations.CreateModel(
            name="DownloadLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("360p", "360p"),
                            ("480p", "480p"),
                            ("720p", "720p"),
                            ("1080p", "1080p"),
                        ],
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("file_size", models.CharField(blank=True, max_length=20)),
                ("host_name", models.CharField(default="unknown", max_length=50)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("fetch_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_links",
                        to="anime.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["quality", "host_name"],
            },
        ),
        migrations.CreateModel(
            name="AnimeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ratings",
                        to="anime.anime",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="anime",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anime.animecategory",
            ),
        ),
        migrations.AddField(
            model_name="anime",
            name="genres",
            field=models.ManyToManyField(blank=True, to="anime.animegenre"),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["episode_id"], name="anime_episo_episode_e25e9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["anime", "episode_number"],
                name="anime_episo_anime_i_31f856_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["is_completed"], name="anime_episo_is_comp_5a5af4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["publish_date"], name="anime_episo_publish_8ed415_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={("anime", "episode_number")},
        ),
        migrations.AddIndex(
            model_name="downloadlink",
            index=models.Index(
                fields=["episode", "quality"], name="anime_downl_episode_dae5be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadlink",
            index=models.Index(
                fields=["host_name"], name="anime_downl_host_na_9651fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadlink",
            index=models.Index(
                fields=["is_active"], name="anime_downl_is_acti_5d1d51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["anime_id"], name="anime_anime_anime_i_6900e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(fields=["status"], name="anime_anime_status_6458e9_idx"),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["is_featured"], name="anime_anime_is_feat_f905ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["is_trending"], name="anime_anime_is_tren_cb4a7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(fields=["year"], name="anime_anime_year_38d697_idx"),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(fields=["title"], name="anime_anime_title_575f9d_idx"),
        ),
    ]
