"""
Django settings for master project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


### to make user admin from shell
# from django.contrib.auth.models import User

# user = User.objects.get(username='john')
# user.is_staff = True
# user.is_superuser = True
# user.save()


from pathlib import Path
import os
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

## test
SECRET_KEY = config('SECRET_KEY', default='your-secret-key-here')
# SECRET_KEY = "fsfcscfsfdsxqc434433trrtygffgdxffgcycfvyfxdtrxerdrtdyfuyttrrd"

DEBUG = config('DEBUG', default=False, cast=bool)
# DEBUG = True
## deploy
# SECRET_KEY = os.environ.get('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!

## deploy
# DEBUG = os.environ.get('DEBUG', 'False') == 'True'



## deploy
ALLOWED_HOSTS = [
    "*"
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Your apps (in this order)
    'main',              # ⭐ Main unified homepage app
    'movies',            # Movies app
    'anime',             # Anime app
    'manga',             # Manga app
    'apk_store',         # Ibez app
    
    # Other apps
    'django_crontab',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]


SITE_ID = 1

MIDDLEWARE = [
     # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '998536136119-hhihes5q9b3e6qim325j5sk8t7i7oq7a.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}

ROOT_URLCONF = 'master.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'main' / 'templates',      # ⭐ Add this line
            BASE_DIR / 'movies' / 'templates',
            BASE_DIR / 'anime' / 'templates',     # Optional: if you have custom templates
            BASE_DIR / 'manga' / 'templates',     # Optional: if you have custom templates
            BASE_DIR / 'apk_store' / 'templates', # Optional: if you have custom templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'movies.context_processors.categories_processor',  # Keep this
            ],
        },
    },
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_LOGIN_ON_GET = True

AUTHENTICATION_BACKENDS = [
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]
WSGI_APPLICATION = 'master.wsgi.application'


PWA_SETTINGS = {
    'name': 'Ibez - Movies, Anime, Manga & Apps',
    'short_name': 'Ibez',
    'description': 'All entertainment in one place. Stream movies, watch anime, read manga, and download premium APKs.',
    'theme_color': '#3b82f6',
    'background_color': '#ffffff',
    'display': 'standalone',
    'scope': '/',
    'start_url': '/',
    'orientation': 'portrait-primary',
    'icons': [
        {
            'src': '/static/img/icons/icon-192x192.png',
            'sizes': '192x192',
            'type': 'image/png',
        },
        {
            'src': '/static/img/icons/icon-512x512.png',
            'sizes': '512x512',
            'type': 'image/png',
        }
    ]
}

# Security settings for PWA
SECURE_REFERRER_POLICY = 'same-origin'


# Content Security Policy for PWA
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.tailwindcss.com", "https://cdnjs.cloudflare.com")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdnjs.cloudflare.com")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://cdnjs.cloudflare.com")
CSP_IMG_SRC = ("'self'", "data:", "https:", "blob:")
CSP_CONNECT_SRC = ("'self'", "https:")
CSP_MANIFEST_SRC = ("'self'",)


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# DATABASES = {
#     'default': dj_database_url.parse(config('DATABASE_URL'))
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}


# postgresql://postgres.scsikofwbmcchkxvrvsw:all_in_one_db@aws-1-eu-west-1.pooler.supabase.com:6543/postgres

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JS, Images)
# URL for static files
STATIC_URL = '/static/'

# Path where collectstatic will gather all static files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Optional: only if you also have extra static folders (e.g., in apps)
STATICFILES_DIRS = [
    BASE_DIR / 'movies' / 'static',
    BASE_DIR / 'main' / 'static',      # ⭐ Add this if you have static files in main
    BASE_DIR / 'pwa_static',           # Keep this
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'Ibez-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# PWA Caching headers
CACHE_CONTROL_MAX_AGE = 31536000  # 1 year for static files

MIDDLEWARE += [
    'movies.middleware.PWAMiddleware',
]

# Add offline page URL
OFFLINE_URL = '/offline.html'

# Push notification settings (optional)
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "your-vapid-public-key-here",
    "VAPID_PRIVATE_KEY": "your-vapid-private-key-here",
    "VAPID_ADMIN_EMAIL": "admin@Ibez.store"
}

INSTALLED_APPS += [
    'pwa',
]

# Add manifest.json to static files
STATICFILES_DIRS.append(BASE_DIR / 'pwa_static')

# Use WhiteNoise to serve static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Auth redirects
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


CRISPY_ALLOWED_TEMPLATE_PACKS = ["bootstrap5"]
CRISPY_TEMPLATE_PACK = "bootstrap5"



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'