# Generated by Django 4.2.7 on 2025-11-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "apk_type",
                    models.CharField(
                        choices=[("game", "Game"), ("app", "App")],
                        default="game",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon_url", models.URLField(blank=True, max_length=500)),
                ("cover_image_url", models.URLField(blank=True, max_length=500)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("size", models.CharField(blank=True, max_length=50)),
                (
                    "android_version",
                    models.CharField(
                        blank=True, help_text="Minimum Android version", max_length=50
                    ),
                ),
                (
                    "architecture",
                    models.CharField(
                        blank=True, help_text="arm7, arm8, x86, etc.", max_length=50
                    ),
                ),
                ("package_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("modded", "Modded"),
                            ("premium", "Premium"),
                            ("pro", "Pro"),
                            ("unlocked", "Unlocked"),
                            ("paid", "Paid"),
                            ("original", "Original"),
                        ],
                        default="modded",
                        max_length=20,
                    ),
                ),
                (
                    "mod_features",
                    models.TextField(
                        blank=True, help_text="Mod features like Unlimited Money, etc."
                    ),
                ),
                ("download_url", models.URLField(blank=True, max_length=1000)),
                ("source_url", models.URLField(max_length=500, unique=True)),
                ("downloads_count", models.CharField(blank=True, max_length=50)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "APK",
                "verbose_name_plural": "APKs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="apk_store.apk",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="apk",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="apks", to="apk_store.category"
            ),
        ),
        migrations.CreateModel(
            name="APKVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("download_url", models.URLField(max_length=1000)),
                ("size", models.CharField(blank=True, max_length=50)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("changelog", models.TextField(blank=True)),
                ("is_latest", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="apk_store.apk",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("apk", "version")},
            },
        ),
        migrations.AddIndex(
            model_name="apk",
            index=models.Index(
                fields=["apk_type", "-created_at"],
                name="apk_store_a_apk_typ_98c113_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apk",
            index=models.Index(fields=["slug"], name="apk_store_a_slug_909a1d_idx"),
        ),
    ]
