# Generated by Django 4.2.7 on 2025-12-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apk_store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("apk", "APK File"),
                            ("obb", "OBB File"),
                            ("data", "Data File"),
                            ("mod", "Mod File"),
                            ("patch", "Patch File"),
                            ("other", "Other"),
                        ],
                        default="apk",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("download_url", models.URLField(max_length=1000)),
                ("size", models.CharField(blank=True, max_length=50)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_files",
                        to="apk_store.apk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Download File",
                "verbose_name_plural": "Download Files",
                "ordering": ["order", "id"],
            },
        ),
    ]
