# Generated by Django 5.1.7 on 2026-03-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_id",
                    models.IntegerField(help_text="PK of the Movie / Anime / Manga"),
                ),
                ("content_title", models.CharField(max_length=500)),
                ("telegram_message_id", models.CharField(blank=True, max_length=100)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-posted_at"],
                "unique_together": {("content_type", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="TelegramUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField()),
                ("content_title", models.CharField(max_length=500)),
                (
                    "update_key",
                    models.CharField(
                        help_text="Episode/chapter identifier", max_length=500
                    ),
                ),
                ("telegram_message_id", models.CharField(blank=True, max_length=100)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-posted_at"],
                "unique_together": {("content_type", "content_id", "update_key")},
            },
        ),
    ]
