# Generated by Django 4.2.7 on 2025-11-23 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PWAInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.TextField()),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("platform", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pwa_installations",
            },
        ),
        migrations.CreateModel(
            name="OfflineAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("action_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "offline_actions",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                (
                    "title_b",
                    models.CharField(
                        blank=True,
                        help_text="Stores new episode info",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("title_b_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_series", models.BooleanField(default=False)),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Mark if series is complete"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("video_url", models.URLField(verbose_name="Video/Embed URL")),
                (
                    "download_url",
                    models.URLField(blank=True, null=True, verbose_name="Download URL"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Cover Image URL"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "scraped",
                    models.BooleanField(
                        default=False,
                        help_text="True if movie was scraped from external API",
                    ),
                ),
                (
                    "is_blockbuster",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as featured/trending for the homepage",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="If user-submitted, the submitting user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.category"
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_movies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watchlisted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="watchlist_movies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DownloadLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_links",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="movies.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField()),
                ("p256dh_key", models.TextField()),
                ("auth_key", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "push_subscriptions",
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
