# Generated by Django 4.2.7 on 2025-12-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=500, unique=True)),
                ("repack_number", models.CharField(blank=True, max_length=20)),
                ("version", models.CharField(blank=True, max_length=200)),
                ("short_description", models.TextField(blank=True)),
                ("full_description", models.TextField(blank=True)),
                ("game_description", models.TextField(blank=True)),
                ("original_size", models.CharField(blank=True, max_length=50)),
                ("repack_size", models.CharField(blank=True, max_length=50)),
                ("languages", models.CharField(blank=True, max_length=500)),
                ("companies", models.CharField(blank=True, max_length=500)),
                ("repack_features", models.TextField(blank=True)),
                ("installation_time", models.CharField(blank=True, max_length=200)),
                ("installation_size", models.CharField(blank=True, max_length=100)),
                ("cover_image", models.URLField(blank=True, max_length=1000)),
                ("post_url", models.URLField(max_length=1000, unique=True)),
                ("post_id", models.IntegerField(unique=True)),
                ("post_date", models.DateTimeField()),
                ("modified_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("updated", "Updated"),
                            ("active", "Active"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scraped_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="pc_games.category"
                    ),
                ),
            ],
            options={
                "ordering": ["-post_date"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minimum_ram", models.CharField(blank=True, max_length=100)),
                ("recommended_ram", models.CharField(blank=True, max_length=100)),
                ("minimum_storage", models.CharField(blank=True, max_length=100)),
                ("os_requirements", models.TextField(blank=True)),
                ("additional_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="pc_games.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=1000)),
                ("thumbnail_url", models.URLField(blank=True, max_length=1000)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="pc_games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("page_url", models.URLField(blank=True, max_length=1000)),
                ("error_details", models.TextField(blank=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraping_logs",
                        to="pc_games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="GameUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_title", models.CharField(max_length=500)),
                ("version_from", models.CharField(blank=True, max_length=200)),
                ("version_to", models.CharField(blank=True, max_length=200)),
                ("download_url", models.URLField(max_length=2000)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("file_name", models.CharField(max_length=500)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="pc_games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="pc_games.tag"
            ),
        ),
        migrations.CreateModel(
            name="DownloadMirror",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mirror_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Download"),
                            ("torrent", "Torrent"),
                            ("magnet", "Magnet Link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "filehoster",
                    models.CharField(
                        choices=[
                            ("datanodes", "DataNodes"),
                            ("fuckingfast", "FuckingFast"),
                            ("multiupload", "MultiUpload"),
                            ("1337x", "1337x"),
                            ("rutor", "RuTor"),
                            ("tapochek", "Tapochek.net"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parts", models.JSONField(blank=True, default=list)),
                ("torrent_url", models.URLField(blank=True, max_length=2000)),
                ("magnet_link", models.TextField(blank=True)),
                ("torrent_file_url", models.URLField(blank=True, max_length=2000)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_mirrors",
                        to="pc_games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "mirror_type"],
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["-post_date"], name="pc_games_ga_post_da_676368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["slug"], name="pc_games_ga_slug_826835_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["post_id"], name="pc_games_ga_post_id_8111d9_idx"
            ),
        ),
    ]
