# Generated by Django 4.2.7 on 2025-12-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pc_games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="companies",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="installation_size",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="game",
            name="installation_time",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="game",
            name="languages",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="original_size",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="game",
            name="repack_size",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="game",
            name="version",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
